### ISSUE TITLE
NowPlaying機能の修正

### ISSUE THREAD

**Issue by atst96** [atst1996/Liberfy#2]
・iTunesAppのインスタンス生成直後にイベント登録するとCOMExceptionが発生する
・WMPLibのメディア情報取得中、アートワークの取得時に範囲外例外が発生する。

**Comment by Asteriskx** [comment]
iTunesLib に関しては、
恐らくですが、iTunes の仕様が変わり
COM を介しての通信が出来なくなったからだと思います。

**Comment by atst96** [comment]
@Asteriskx iTunesLibについてですが、最近こちらの環境でiTunes自体が不安定な状態だったのもあり、iTunesの再インストールやAppData，ミュージックフォルダ内のiTunes関連ファイルの消去、干渉していると思しきドライバの削除を行ったところ、
> ・iTunesAppのインスタンス生成直後にイベント登録するとCOMExceptionが発生する

が解決しました。

また、それ以前ではiTunesAppインスタンスの生成から数秒おいてからのイベント登録に関しては特に問題なかったので、不具合（COM関連の処理に時間がかかっているとか？）なのかもしれないですね
